import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Layout from "../components/layout/index";
import { colors } from "../styles/theme";
import Button from "../components/button/index";
import { gitHubLogin, onAuthChange } from "../firebase/client";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthChange((authUser) => setUser(authUser));
  }, []);

  const handleClick = () => {
    gitHubLogin().then((userInfo) => {
      setUser(userInfo);
      //console.log("USER: ", user);
    });
  };

  console.log("USER: ", user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Social App 👾</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className={styles.main}>
        <section>
          <img src="/curly_bracket.png" alt="logo" />
          <h3>Dev network for devs</h3>
          <div>
            {user === null ? (
              <Button onClick={handleClick}>Login with Github</Button>
            ) : (
              <div>
                <img src={user.userAvatar} alt="" />
                <p>{`Bienvenido ${user.userName}`}</p>
              </div>
            )}
          </div>
        </section>
      </Layout>

      <style jsx>
        {`
          section {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100%;
          }

          img {
            width: 10%;
          }

          h3 {
            color: ${colors.primary};
          }
        `}
      </style>
    </div>
  );
}
